(* ------------------------------------------------------------------- *)
(*                                                                     *)
(*  This file should consist of two lines of code after this long      *)
(*  comment.                                                           *)
(*                                                                     *)
(*  UNIX:                                                              *) 
(*       The code after this comment should be                         *)
(*  NCGBSetLatexCommand["latex"];                                      *)
(*  NCGBSetDviCommand["xdvi "];                                        *)
(*                                                                     *)
(*  WINDOWS (Works at UCSD on 2nd floor?)                              *)
(*       The code after this comment should be                         *)
(*  NCGBSetLatexCommand["c:\\\\texmf\\\\miktex\\\\bin\\\\latex.exe"];  *) 
(*  NCGBSetDviCommand["c:\\texmf\\miktex\\bin\\yap.Exe"];              *)
(*                                                                     *)
(*  WINDOWS (Works at UCSD on other floors?)                           *)
(*       The code after this comment should be                         *)
(*  NCGBSetLatexCommand["c:\\latex\\miktex\\bin\\latex.exe"];          *)
(*  NCGBSetDviCommand[""c:\\latex\\miktex\\bin\\yap.Exe"];             *)
(*                                                                     *)
(* ------------------------------------------------------------------- *)

NCGBSetLatexCommand["latex"];
NCGBSetDviCommand["xdvi"];
