include ../make.inc

FILES = NonCommutativeMultiply.usage \
	NCCollect.usage \
	NCSimplifyRational.usage \
	NCDiff.usage \
	NCReplace.usage \
	NCSelfAdjoint.usage \
	NCOutput.usage \
	NCMatMult.usage \
	NCPolynomial.usage \
	NCSylvester.usage \
	NCQuadratic.usage \
	NCRational.usage \
	NCConvexity.usage \
	NCConvexity.private.usage \
	NCRealization.usage \
	NCRealization.private.usage \
        NCMatrixDecompositions.usage \
        MatrixDecompositions.usage \
	NCUtil.usage

all: $(FILES)

clean:
	rm -f $(FILES)

install:
	mv $(FILES) ../../NCAlgebra/.
