include ../make.inc

FILES = NCSDP.usage \
	SDP.usage \
	SDPFlat.usage \
	SDPSylvester.usage \
	PrimalDual.usage \
	Sylvester.usage

all: $(FILES)

clean:
	rm -f $(FILES)

install:
	mv $(FILES) ../../NCSDP/.
